[build]
  publish = "src"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

# 确保 .gif 等静态资源被正确提供
[[headers]]
  for = "/resources/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
